export const action_type = {
    SELECTED_USER_TYPE: 'SELECTED_USER_TYPE',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    ALERT_SNACK_BAR: 'ALERT_SNACK_BAR',
    ADD_NEW_VIDEO: 'ADD_NEW_VIDEO',
    DELETE_NEW_VIDEO: 'DELETE_NEW_VIDEO',
    FETCH_VIDEO: 'FETCH_VIDEO',
    FETCH_FOOTER_VIDEO: 'FETCH_FOOTER_VIDEO',
    ADD_NEW_FOOTER_VIDEO: 'ADD_NEW_FOOTER_VIDEO',
    DELETE_FOOTER_VIDEO: 'DELETE_FOOTER_VIDEO',

    // CUSTOMER ACTION TYPE
    FETCH_CUSTOMERS: 'FETCH_CUSTOMERS',
    ADD_CUSTOMER: 'ADD_CUSTOMER',
    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
    DELETE_CUSTOMER: 'DELETE_CUSTOMER',
    FETCH_CUSTOMER_BY_ID: 'FETCH_CUSTOMER_BY_ID',

    // ISP ACTION TYPE
    FETCH_ISP_USERS: 'FETCH_ISP_USERS',
    FECTCH_ISP_USER_BY_ID: 'FECTCH_ISP_USER_BY_ID',
    UPDATE_ISP_USER: 'UPDATE_ISP_USER',
    DELETE_ISP_USER: 'DELETE_ISP_USER',
    TOOGLE_ISP_ADD_MODAL: 'TOOGLE_ISP_ADD_MODAL',
    
    // WEB CAM CAPTURE ACTION TYPE
    ALLOW_CAMERA: 'ALLOW_CAMERA',
    ADD_AVAILABLE_CAMERAS: 'ADD_AVAILABLE_CAMERAS',
    SET_SELECTED_CAMERA: 'SET_SELECTED_CAMERA',
    SET_PERMISSION_STATUS: 'SET_PERMISSION_STATUS',
    ADD_CLIENT_PHOTO: 'ADD_CLIENT_PHOTO',
    RESET_CLIENT_PHOTO: 'RESET_CLIENT_PHOTO',
    DELETE_CLIENT_PHOTO: 'DELETE_CLIENT_PHOTO',
    RESET_PHOTOS: 'RESET_PHOTOS',
    FETCH_CLIENT: 'FETCH_CLIENT',
    FETCH_CLIENT_BY_ID: 'FETCH_CLIENT_BY_ID',
    ADD_CLIENT: 'ADD_CLIENT',
    SET_SELECT_CLIENT: 'SET_SELECT_CLIENT',
    CLIENT_UPDATE_MODAL_STATUS: 'CLIENT_UPDATE_MODAL_STATUS',
    SELECT_FOR_UPDATE_CLIENT: 'SELECT_FOR_UPDATE_CLIENT',
    SELECTED_CLIEND_DATA: 'SELECTED_CLIEND_DATA',
    CLIENT_ADD_MODAL_STATUS: 'CLIENT_ADD_MODAL_STATUS',

    // CAMERA VOICE ACTION TYPE
    FETCH_ALL_CAMERA_VOICE: 'FETCH_ALL_CAMERA_VOICE',
    FETCH_CAMERA_VOICE_BY_ID: 'FETCH_CAMERA_VOICE_BY_ID',
    ADD_CAMERA_VOICE: 'ADD_CAMERA_VOICE',
    UPDATE_CAMERA_VOICE: 'UPDATE_CAMERA_VOICE',
    DELETE_CAMERA_VOICE: 'DELETE_CAMERA_VOICE',

    // COLORING PAGE ACTION TYPE
    FETCH_ALL_COLORING_PAGE: 'FETCH_ALL_COLORING_PAGE',
    FETCH_COLORING_PAGE_BY_ID: 'FETCH_COLORING_PAGE_BY_ID',
    ADD_COLORING_PAGE: 'ADD_COLORING_PAGE',
    UPDATE_COLORING_PAGE: 'UPDATE_COLORING_PAGE',
    DELETE_COLORING_PAGE: 'DELETE_COLORING_PAGE',

    // CAMERA ACTION TYPE
    FETCH_ALL_CAMERA: 'FETCH_ALL_CAMERA',
    FETCH_CAMERA_BY_ID: 'FETCH_CAMERA_BY_ID',
    ADD_CAMERA: 'ADD_CAMERA',
    DELETE_CAMERA: 'DELETE_CAMERA',
    UPDATE_CAMERA: 'UPDATE_CAMERA',
    CAMERA_UPDATE_MODAL_STATUS: 'CAMERA_UPDATE_MODAL_STATUS',
    CAMERA_ADD_MODAL_STATUS: 'CAMERA_ADD_MODAL_STATUS',
    SELECT_FOR_UPDATE_CAMERA: 'SELECT_FOR_UPDATE_CAMERA',
    SELECTED_CAMERA_DATA: 'SELECTED_CAMERA_DATA',
    UPDATE_CAMERA_STATUS: 'UPDATE_CAMERA_STATUS',

    // Exit Email Action Type

    FETCH_ALL_EXIT_EMAIL: 'FETCH_ALL_EXIT_EMAIL',
    FETCH_EXIT_EMAIL_BY_ID: 'FETCH_EXIT_EMAIL_BY_ID',
    ADD_EXIT_EMAIL: 'ADD_EXIT_EMAIL',
    UPDATE_EXIT_EMAIL: 'UPDATE_EXIT_EMAIL',
    DELETE_EXIT_EMAIL: 'DELETE_EXIT_EMAIL',

    FETCH_ALL_COMPLETED_VIDEOS: 'FETCH_ALL_COMPLETED_VIDEOS',
    ADD_COMPLETED_VIDEOS: 'ADD_COMPLETED_VIDEOS',
    SET_RESEND_EMAIL: 'SET_RESEND_EMAIL',

    FETCH_ALL_TOURPLACE : 'FETCH_ALL_TOURPLACE',
    FETCH_TOURPLACE_BY_ID : 'FETCH_TOURPLACE_BY_ID',
    ADD_TOURPLACE : 'ADD_TOURPLACE',
    DELETE_TOURPLACE : 'DELETE_TOURPLACE',
    UPDATE_TOURPLACE : 'UPDATE_TOURPLACE',
    UPDATE_TOURPLACE_STATUS : 'UPDATE_TOURPLACE_STATUS',
    TOURPLACE_UPDATE_MODAL_STATUS : 'TOURPLACE_UPDATE_MODAL_STATUS',
    TOURPLACE_ADD_MODAL_STATUS : 'TOURPLACE_ADD_MODAL_STATUS',
    SELECT_FOR_UPDATE_TOURPLACE : 'SELECT_FOR_UPDATE_TOURPLACE',

    // PRICING ACTION TYPE
    FETCH_ALL_PRICING: 'FETCH_ALL_PRICING',
    FETCH_PRICING_BY_ID: 'FETCH_PRICING_BY_ID',
    ADD_PRICING: 'ADD_PRICING',
    DELETE_PRICING: 'DELETE_PRICING',
    UPDATE_PRICING: 'UPDATE_PRICING',
    PRICING_UPDATE_MODAL_STATUS: 'PRICING_UPDATE_MODAL_STATUS',
    PRICING_ADD_MODAL_STATUS: 'PRICING_ADD_MODAL_STATUS',
    SELECT_FOR_UPDATE_PRICING: 'SELECT_FOR_UPDATE_PRICING',
    SELECTED_PRICING_DATA: 'SELECTED_PRICING_DATA',
    SET_SELECT_PRICE_FOR_BUY: 'SET_SELECT_PRICE_FOR_BUY',
    SHOW_PAY_MODAL: 'SHOW_PAY_MODAL',

    FETCH_ALL_CLIENTS: 'FETCH_ALL_CLIENTS',
    FECTCH_CLIENT_BY_ID: 'FECTCH_CLIENT_BY_ID',
    UPDATE_CLIENT: 'UPDATE_CLIENT',
    DELETE_CLIENT: 'DELETE_CLIENT',

    FETCH_ALL_INVOICE: 'FETCH_ALL_INVOICE',
    FETCH_ALL_VALID_INVOICE: 'FETCH_ALL_VALID_INVOICE',
    ADD_VALID_INVOICE: 'ADD_VALID_INVOICE',
    UPADTE_SELECTEDCLIENTSDATA: 'UPADTE_SELECTEDCLIENTSDATA'
}