export const invoice_mock_data = [
    {
        username: 'Steven Stence',
        email: 'test@test.com',
        phone_number: '+125689743',
        tour_place: '1880 Town',
        amount: 10,
        create_at: '2020-09-08',
        status: 'PENDING',
        message: 'The payment is in pending',
        remains: 3,
    },
    {
        username: 'Max Jerry',
        email: 'test@test.com',
        phone_number: '+125689743',
        tour_place: 'Macdonald',
        amount: 20,
        create_at: '2020-09-10',
        status: 'COMPLETED',
        message: '',
        remains: 3,
    },
    {
        username: 'William Rodgers',
        email: 'test@test.com',
        phone_number: '+15684635',
        tour_place: 'House View',
        amount: 30,
        create_at: '2020-09-22',
        status: 'APPROVED',
        message: 'Your payment will be successed soon',
        remains: 3,
    },
    {
        username: 'Jerry Moxa',
        email: 'test@test.com',
        phone_number: '+5486315355',
        tour_place: 'Petty Zon',
        amount: 45,
        create_at: '2020-02-08',
        status: 'CANCELED',
        message: 'Your payment was canceled',
        remains: 3,
    },
    {
        username: 'Jerry Moxa',
        email: 'test@test.com',
        phone_number: '+5486315355',
        tour_place: 'Petty Zon',
        amount: 45,
        create_at: '2020-02-08',
        status: 'VOIDED',
        message: 'Your payment was voided',
        remains: 3,
    },
    {
        username: 'Jerry Moxa',
        email: 'test@test.com',
        phone_number: '+5486315355',
        tour_place: 'Petty Zon',
        amount: 45,
        create_at: '2020-02-08',
        status: 'REFUNDED',
        message: 'Your payment was refunded',
        remains: 3,
    },
    {
        username: 'Jerry Moxa',
        email: 'test@test.com',
        phone_number: '+5486315355',
        tour_place: 'Petty Zon',
        amount: 45,
        create_at: '2020-02-08',
        status: 'DECLINED',
        message: 'Your payment was declined',
        remains: 3,
    },
    {
        username: 'Jerry Moxa',
        email: 'test@test.com',
        phone_number: '+5486315355',
        tour_place: 'Petty Zon',
        amount: 45,
        create_at: '2020-02-08',
        status: 'INSUFFCIENT_FUNDS',
        message: 'You do not have enough money',
        remains: 3,
    },
    {
        username: 'Jerry Moxa',
        email: 'test@test.com',
        phone_number: '+5486315355',
        tour_place: 'Petty Zon',
        amount: 45,
        create_at: '2020-02-08',
        status: 'CARD_EXPIRED',
        message: 'Your card was expired',
        remains: 3,
    },
    {
        username: 'Jerry Moxa',
        email: 'test@test.com',
        phone_number: '+5486315355',
        tour_place: 'Petty Zon',
        amount: 45,
        create_at: '2020-02-08',
        status: 'CARD_DECLINED',
        message: 'Your card was declined',
        remains: 3,
    },
    {
        username: 'Jerry Moxa',
        email: 'test@test.com',
        phone_number: '+5486315355',
        tour_place: 'Petty Zon',
        amount: 45,
        create_at: '2020-02-08',
        status: 'INVALID_CARD',
        message: 'Your card is invalid',
        remains: 3,
    },
    {
        username: 'Jerry Moxa',
        email: 'test@test.com',
        phone_number: '+5486315355',
        tour_place: 'Petty Zon',
        amount: 45,
        create_at: '2020-02-08',
        status: 'FRAUD_DETECTED',
        message: 'Your card is scammer',
        remains: 3,
    },
    {
        username: 'Jerry Moxa',
        email: 'test@test.com',
        phone_number: '+5486315355',
        tour_place: 'Petty Zon',
        amount: 45,
        create_at: '2020-02-08',
        status: 'unknown',
        message: 'Your payment was not processed for unknown reason',
        remains: 3,
    },
    {
        username: 'Jerry Moxa',
        email: 'test@test.com',
        phone_number: '+5486315355',
        tour_place: 'Petty Zon',
        amount: 45,
        create_at: '2020-02-08',
        status: 'VERSION_EXPIRES',
        message: 'Your version is expired',
        remains: 0,
    },
]